"""empty message

Revision ID: 957fdf6b3ca7
Revises: 
Create Date: 2023-12-11 20:38:02.784390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957fdf6b3ca7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre'))
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie'))
    )
    op.create_table('question2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question2'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('set_weight', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('genre_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('genre_weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_genre_weight_genre_id_genre')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_genre_weight_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre_weight'))
    )
    op.create_table('movie_genre_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_movie_genre_association_genre_id_genre')),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_movie_genre_association_movie_id_movie'))
    )
    op.create_table('question1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=40), nullable=False),
    sa.Column('weather', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_question1_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question1'))
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sunny1', sa.String(length=10), nullable=True),
    sa.Column('sunny2', sa.String(length=10), nullable=True),
    sa.Column('sunny3', sa.String(length=10), nullable=True),
    sa.Column('sunny4', sa.String(length=10), nullable=True),
    sa.Column('cloudy1', sa.String(length=10), nullable=True),
    sa.Column('cloudy2', sa.String(length=10), nullable=True),
    sa.Column('cloudy3', sa.String(length=10), nullable=True),
    sa.Column('cloudy4', sa.String(length=10), nullable=True),
    sa.Column('snowy1', sa.String(length=10), nullable=True),
    sa.Column('snowy2', sa.String(length=10), nullable=True),
    sa.Column('raining1', sa.String(length=10), nullable=True),
    sa.Column('raining2', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_weather_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather')
    op.drop_table('question1')
    op.drop_table('movie_genre_association')
    op.drop_table('genre_weight')
    op.drop_table('user')
    op.drop_table('question2')
    op.drop_table('movie')
    op.drop_table('genre')
    # ### end Alembic commands ###
