"""empty message

Revision ID: d0d295babde6
Revises: 
Create Date: 2023-12-10 18:05:02.426709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d295babde6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre'))
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movie'))
    )
    op.create_table('question2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question2'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('genre_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('interest_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_genre_interest_genre_id_genre')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_genre_interest_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genre_interest'))
    )
    op.create_table('movie_genre_association',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name=op.f('fk_movie_genre_association_genre_id_genre')),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name=op.f('fk_movie_genre_association_movie_id_movie'))
    )
    op.create_table('question1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=40), nullable=False),
    sa.Column('weather', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_question1_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question1'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question1')
    op.drop_table('movie_genre_association')
    op.drop_table('genre_interest')
    op.drop_table('user')
    op.drop_table('question2')
    op.drop_table('movie')
    op.drop_table('genre')
    # ### end Alembic commands ###
